yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(verbose_name='Полное название группы',
                             max_length=200,
                             help_text='Введите название группы')
    slug = models.SlugField(verbose_name='Slug-key of the group', unique=True)
    description = models.TextField(verbose_name='Описание группы')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста',
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField(verbose_name='Дата поста',
                                    auto_now_add=True)
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа этого поста',
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        help_text='Выберите группу'
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from .models import Post
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        labels = {
            'text': 'Текст поста',
            'group': 'Group'
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой относится пост'
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

yatube/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

yatube/posts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Post, Group, User
from django.core.paginator import Paginator
from .forms import PostForm
from django.contrib.auth.decorators import login_required


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    template = 'posts/group_list.html'
    return render(request, template, context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    num = post_list.count()
    context = {
        "page_obj": page_obj,
        "num": num,
        "name": user,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author_all_posts = post.author.posts.all()
    num_of_posts = author_all_posts.count()
    text = post.text[:30]
    context = {
        "post": post,
        "text": text,
        "num": num_of_posts,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    username = request.user.username
    form = PostForm(request.POST)
    if form.is_valid() and request.method == 'POST':
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=username)
    return render(request, 'posts/post_create.html',
                           {'form': form, 'is_edit': False})


def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(request.POST, instance=post)
    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/post_create.html',
                           {'form': form, 'is_edit': True,
                            'post_id': post_id})

yatube/users/views.py
from django.views.generic import CreateView
# Функция reverse_lazy позволяет получить URL по параметрам функции path()
# Берём, тоже пригодится
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
</p>
{% endblock %} 

yatube/templates/about/tech.html
<!-- templates/about/tech.html -->
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html> 
<html lang="ru">
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">     
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
     
    <link rel="icon" href="{% static 'img/fav/fav.ico' type='image' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <title>
      {% block title %}
      {% endblock %}
    </title>
     
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/core/403csrf.html
# templates/core/403csrf.html
{% extends "base.html" %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/includes/header.html
<!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
<!-- В дальнейшем тут будет создано полноценное меню -->    
{% load static %}
{% with request.resolver_match.view_name as view_name %}  
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <!-- ссылка должна вести на главную страницу -->
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static "img/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
      <span style="color:red">Ya</span>tube
    </a>
      {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов 
      {% endcomment %}
      <ul class="nav nav-pills">
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" 
          href="{% url 'about:author' %}">
            Об авторе
          </a>
        </li>
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" 
          href="{% url 'about:tech' %}">
            Технологии
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">              
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" 
          href="{% url 'posts:post_create' %}">
            Новая запись
          </a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="">Изменить пароль</a>
        </li>
        <li class="nav-item">              
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" 
          href="{% url 'users:logout' %}">
            Выйти
          </a>
        </li>
          Пользователь: {{ user.username }}
        <li>
        {% else %}
        <li class="nav-item">              
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" 
          href="{% url 'users:login' %}">
            Войти
          </a>
        </li>
        <li class="nav-item">              
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" 
          href="{% url 'users:signup' %}">
            Регистрация
          </a>
        </li>
        {% endif %}
      </ul>
  </div>
</nav>      
{% endwith %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 

{% block title %}
  Записи сообщества {{ page_odj.group.title }}
{% endblock %}

{% block content %} 
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container">
    <h1>{{ group.title }}</h1>
    <p>{{group.description}}</p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href={% url "posts:profile" post.author %}>все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      </article>
      <a href="{% url "posts:group_posts" post.group.slug %}">все записи группы</a>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div> 
{% endblock %} 

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %} 

yatube/templates/posts/index.html
{% extends 'base.html' %} 
  
{% block title %}
  Последние обновления на сайте
{% endblock %}   

{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href={% url "posts:profile" post.author %}>все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
  {% include 'posts/includes/paginator.html' %}
{% endblock %}  

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title%}
  {% if is_edit %}
    Новый пост
  {% else %}
    Редактировать запись
  {% endif %}      
{% endblock %}


{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
            {% if is_edit %}
              Новый пост
            {% else %}
              Редактировать запись
            {% endif %}             
        </div>
          <div class="card-body">

          {# Проверка на ошибки #}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}   

          {# Шаблон формы #}
            <form method="post"
              {% if is_edit %} action=
                "{% url 'posts:post_edit' post_id %}"
              {% else %} action=
                "{% url 'posts:post_create' %}"
              {% endif %}>
              {% csrf_token %}
              {% for field in form %}
                <div class="fieldWrapper">
                  <div class="form-group row my-3 p-3">
                    {{ field.errors }}
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                    </label>
                    {{ field }}
                    <small id="id_text-help" class="form-text text-muted">{{ field.help_text }}</small>
                  </div>
                </div>
              {% endfor %}
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}               
                </button> 
            </form>
          </div>
      </div>
    </div>
  </div>
 </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 

    <!-- Подключены иконки, стили и заполенены мета теги -->
{% block title %}
  Пост {{ text }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации:  {{ post.pub_date }}
        </li>
        <!-- если у поста есть группа -->
        {% if post.group %}  
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_posts' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }} {{ post.author }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ num }}</span>
        </li>
        <li class="list-group-item">
          <a href={% url "posts:profile" post.author %}>
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
        {{ post.text }}
      </p>
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %} 

{% block title %}
Профайл пользователя
{% endblock %}

{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ name.get_full_name }}</h1>
    <h3>Всего постов: {{ num }} </h3>   
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Дата публикации: {{ post.pub_date }}
          </li>
        </ul>
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      </article>
      {% if post.group %}       
        <a href="{% url "posts:group_posts" post.group.slug %}">все записи группы</a>        
      {% endif %}
      <hr>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
        <!-- Остальные посты. после последнего нет черты -->
        <!-- Здесь подключён паджинатор -->  
  </div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}

{% block title %}Войти{% endblock %}

{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            Забыли пароль?
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% load static %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}